import { NextResponse } from "next/server";
import connectDB from "../../../lib/mongodb";
import SurgeryPackage from "../../../models/SurgeryPackage";

export const dynamic = "force-dynamic";

const testPackages = [
  {
    packageId: "SURG-001",
    hospitalName: "Patna Medical Center",
    name: "Laparoscopic Cholecystectomy (Gallbladder Removal)",
    category: "Laparoscopic Surgery",
    description: "Minimally invasive gallbladder removal surgery with latest laparoscopic technology.",
    inclusions: ["Pre-op tests", "Surgery", "Anesthesia", "ICU (if needed)", "Post-op care", "Medicines"],
    mrp: 75000,
    offerPrice: 55000,
    membershipDiscount: 10,
    membershipPrice: 49500,
    roomType: "Private",
    roomOptions: [
      { type: "General", extraCharge: 0 },
      { type: "Private", extraCharge: 5000 },
      { type: "Deluxe", extraCharge: 10000 },
    ],
    stayDays: 2,
    foodIncluded: true,
    foodDetails: "Vegetarian meals 3 times/day",
    surgeonName: "Dr. Rajesh Kumar",
    surgeonDegrees: ["MBBS", "MS Surgery", "FACS"],
    surgeonExperience: 18,
    pickupFromHome: true,
    pickupCharge: 0,
    dropAvailable: true,
    preSurgeryTests: ["Blood Test", "ECG", "Ultrasound Abdomen", "Chest X-Ray"],
    postCareIncluded: true,
    followUpConsultations: 2,
    address: { district: "Patna", city: "Patna", state: "Bihar" },
    rating: 4.7,
    totalReviews: 85,
    isActive: true,
  },
  {
    packageId: "SURG-002",
    hospitalName: "Brims Hospital Patna",
    name: "Appendectomy (Appendix Removal)",
    category: "General Surgery",
    description: "Safe and effective appendix removal surgery with experienced surgical team.",
    inclusions: ["Pre-op tests", "Surgery", "Anesthesia", "2 nights stay", "Medicines", "Post-op dressing"],
    mrp: 45000,
    offerPrice: 32000,
    membershipDiscount: 15,
    membershipPrice: 27200,
    roomType: "Semi-Private",
    roomOptions: [
      { type: "General", extraCharge: 0 },
      { type: "Semi-Private", extraCharge: 3000 },
      { type: "Private", extraCharge: 7000 },
    ],
    stayDays: 2,
    foodIncluded: true,
    foodDetails: "Light diet meals included",
    surgeonName: "Dr. Amit Singh",
    surgeonDegrees: ["MBBS", "MS General Surgery"],
    surgeonExperience: 12,
    pickupFromHome: true,
    pickupCharge: 500,
    dropAvailable: true,
    preSurgeryTests: ["Blood Test", "ECG", "CT Scan Abdomen"],
    postCareIncluded: true,
    followUpConsultations: 1,
    address: { district: "Patna", city: "Patna", state: "Bihar" },
    rating: 4.5,
    totalReviews: 62,
    isActive: true,
  },
  {
    packageId: "SURG-003",
    hospitalName: "Heart Care Hospital",
    name: "Coronary Angioplasty (Single Stent)",
    category: "Cardiac Surgery",
    description: "Advanced heart procedure to open blocked arteries with stent placement.",
    inclusions: ["Angiography", "Stent", "ICU stay", "Medicines", "Cardiac monitoring", "Diet consultation"],
    mrp: 200000,
    offerPrice: 150000,
    membershipDiscount: 8,
    membershipPrice: 138000,
    roomType: "Suite",
    roomOptions: [
      { type: "Private", extraCharge: 0 },
      { type: "Deluxe", extraCharge: 10000 },
      { type: "Suite", extraCharge: 25000 },
    ],
    stayDays: 4,
    foodIncluded: true,
    foodDetails: "Cardiac diet meals, dietician consultation",
    surgeonName: "Dr. Sunil Verma",
    surgeonDegrees: ["MBBS", "MD Medicine", "DM Cardiology"],
    surgeonExperience: 22,
    pickupFromHome: false,
    dropAvailable: true,
    preSurgeryTests: ["ECG", "Echo", "Blood Tests", "Chest X-Ray", "Angiography"],
    postCareIncluded: true,
    followUpConsultations: 3,
    address: { district: "Patna", city: "Patna", state: "Bihar" },
    rating: 4.9,
    totalReviews: 120,
    isActive: true,
  },
  {
    packageId: "SURG-004",
    hospitalName: "Bone & Joint Hospital",
    name: "Total Knee Replacement",
    category: "Orthopedic Surgery",
    description: "Complete knee joint replacement with imported implants for long-lasting relief.",
    inclusions: ["Implant cost", "Surgery", "Physiotherapy (10 sessions)", "Medicines", "4 nights stay"],
    mrp: 180000,
    offerPrice: 130000,
    membershipDiscount: 12,
    membershipPrice: 114400,
    roomType: "Private",
    roomOptions: [
      { type: "General", extraCharge: 0 },
      { type: "Private", extraCharge: 8000 },
      { type: "Deluxe", extraCharge: 15000 },
    ],
    stayDays: 5,
    foodIncluded: true,
    foodDetails: "High protein diet for recovery",
    surgeonName: "Dr. Vikram Jha",
    surgeonDegrees: ["MBBS", "MS Orthopedics", "Fellowship Joint Replacement"],
    surgeonExperience: 15,
    pickupFromHome: true,
    pickupCharge: 0,
    dropAvailable: true,
    preSurgeryTests: ["Blood Tests", "ECG", "X-Ray Knee", "Echo (if needed)"],
    postCareIncluded: true,
    followUpConsultations: 4,
    address: { district: "Muzaffarpur", city: "Muzaffarpur", state: "Bihar" },
    rating: 4.6,
    totalReviews: 48,
    isActive: true,
  },
  {
    packageId: "SURG-005",
    hospitalName: "Women Care Hospital",
    name: "Normal Delivery Package",
    category: "Gynecology",
    description: "Complete normal delivery package with experienced gynecologist and neonatal care.",
    inclusions: ["Delivery", "OT charges", "Baby care", "2 nights stay", "Medicines", "Pediatrician visit"],
    mrp: 25000,
    offerPrice: 18000,
    membershipDiscount: 20,
    membershipPrice: 14400,
    roomType: "Semi-Private",
    roomOptions: [
      { type: "General", extraCharge: 0 },
      { type: "Semi-Private", extraCharge: 2000 },
      { type: "Private", extraCharge: 5000 },
    ],
    stayDays: 2,
    foodIncluded: true,
    foodDetails: "Special post-delivery diet",
    surgeonName: "Dr. Anjali Singh",
    surgeonDegrees: ["MBBS", "MS Gynecology", "Fellowship Maternal Medicine"],
    surgeonExperience: 14,
    pickupFromHome: true,
    pickupCharge: 0,
    dropAvailable: true,
    preSurgeryTests: ["Blood Tests", "Ultrasound", "BP monitoring"],
    postCareIncluded: true,
    followUpConsultations: 2,
    address: { district: "Patna", city: "Patna", state: "Bihar" },
    rating: 4.8,
    totalReviews: 95,
    isActive: true,
  },
];

export async function GET() {
  try {
    await connectDB();
    await SurgeryPackage.deleteMany({});
    await SurgeryPackage.insertMany(testPackages);
    return NextResponse.json({
      success: true,
      message: `${testPackages.length} surgery packages add ho gaye!`,
    });
  } catch (error) {
    return NextResponse.json(
      { success: false, message: error.message },
      { status: 500 }
    );
  }
}