import { NextResponse } from "next/server";
import connectDB from "../../../lib/mongodb";
import LabTest from "../../../models/LabTest";

export const dynamic = "force-dynamic";

const seedData = [
  {
    testId: "LAB-001",
    hospitalName: "Patna Diagnostics Centre",
    name: "Complete Blood Count (CBC)",
    category: "Blood Test",
    description: "Khoon ki poori jaanch — Hemoglobin, WBC, Platelets aur Red Cells",
    sampleType: "Blood",
    turnaroundTime: "Same Day",
    reportDelivery: "Both",
    mrp: 500,
    offerPrice: 299,
    membershipDiscount: 15,
    membershipPrice: 254,
    homeCollection: true,
    homeCollectionCharge: 50,
    fastingRequired: false,
    address: { district: "Patna", city: "Patna", state: "Bihar" },
    rating: 4.5,
    totalReviews: 120,
    isActive: true,
  },
  {
    testId: "LAB-002",
    hospitalName: "Gaya Health Lab",
    name: "HbA1c (Diabetes Test)",
    category: "Blood Test",
    description: "3 mahine ki average blood sugar — diabetes aur pre-diabetes janch",
    sampleType: "Blood",
    turnaroundTime: "24 hours",
    reportDelivery: "Both",
    mrp: 800,
    offerPrice: 499,
    membershipDiscount: 20,
    membershipPrice: 399,
    homeCollection: true,
    homeCollectionCharge: 50,
    fastingRequired: false,
    preparationNotes: "Khaane ke 2 ghante baad sample lena behtar hai",
    address: { district: "Gaya", city: "Gaya", state: "Bihar" },
    rating: 4.3,
    totalReviews: 85,
    isActive: true,
  },
  {
    testId: "LAB-003",
    hospitalName: "Muzaffarpur Imaging Centre",
    name: "Chest X-Ray",
    category: "X-Ray",
    description: "Seene ki X-Ray — Lungs, Heart aur Ribs ki jaanch",
    sampleType: "N/A",
    turnaroundTime: "Same Day",
    reportDelivery: "Both",
    mrp: 600,
    offerPrice: 350,
    membershipDiscount: 10,
    membershipPrice: 315,
    homeCollection: false,
    homeCollectionCharge: 0,
    fastingRequired: false,
    address: { district: "Muzaffarpur", city: "Muzaffarpur", state: "Bihar" },
    rating: 4.6,
    totalReviews: 200,
    isActive: true,
  },
  {
    testId: "LAB-004",
    hospitalName: "Patna Diagnostics Centre",
    name: "Lipid Profile",
    category: "Blood Test",
    description: "Cholesterol aur triglycerides ki poori jaanch — heart risk assessment",
    sampleType: "Blood",
    turnaroundTime: "Same Day",
    reportDelivery: "Both",
    mrp: 900,
    offerPrice: 599,
    membershipDiscount: 15,
    membershipPrice: 509,
    homeCollection: true,
    homeCollectionCharge: 50,
    fastingRequired: true,
    fastingHours: 12,
    preparationNotes: "12 ghante ka fast zaruri hai — raat ko khaana khake subah sample dena",
    address: { district: "Patna", city: "Patna", state: "Bihar" },
    rating: 4.4,
    totalReviews: 95,
    isActive: true,
  },
  {
    testId: "LAB-005",
    hospitalName: "Bhagalpur Scan Centre",
    name: "Ultrasound — Whole Abdomen",
    category: "Ultrasound",
    description: "Pait ke andar sabhi organs ki sonography — Liver, Kidney, Gall Bladder",
    sampleType: "N/A",
    turnaroundTime: "Same Day",
    reportDelivery: "Both",
    mrp: 1500,
    offerPrice: 999,
    membershipDiscount: 12,
    membershipPrice: 879,
    homeCollection: false,
    homeCollectionCharge: 0,
    fastingRequired: true,
    fastingHours: 6,
    preparationNotes: "6 ghante ka fast aur full bladder (paani piye) leke aayein",
    address: { district: "Bhagalpur", city: "Bhagalpur", state: "Bihar" },
    rating: 4.7,
    totalReviews: 310,
    isActive: true,
  },
  {
    testId: "LAB-006",
    hospitalName: "Darbhanga Medical Lab",
    name: "Thyroid Profile (T3, T4, TSH)",
    category: "Blood Test",
    description: "Thyroid gland ki poori functioning jaanch",
    sampleType: "Blood",
    turnaroundTime: "24 hours",
    reportDelivery: "Both",
    mrp: 1200,
    offerPrice: 749,
    membershipDiscount: 18,
    membershipPrice: 614,
    homeCollection: true,
    homeCollectionCharge: 60,
    fastingRequired: false,
    address: { district: "Darbhanga", city: "Darbhanga", state: "Bihar" },
    rating: 4.2,
    totalReviews: 68,
    isActive: true,
  },
  {
    testId: "LAB-007",
    hospitalName: "Nalanda Diagnostic Hub",
    name: "ECG (Electrocardiogram)",
    category: "ECG",
    description: "Dil ki electrical activity jaanch — Heart rate aur rhythm",
    sampleType: "N/A",
    turnaroundTime: "Same Day",
    reportDelivery: "Physical",
    mrp: 400,
    offerPrice: 199,
    membershipDiscount: 10,
    membershipPrice: 179,
    homeCollection: false,
    homeCollectionCharge: 0,
    fastingRequired: false,
    address: { district: "Nalanda", city: "Bihar Sharif", state: "Bihar" },
    rating: 4.5,
    totalReviews: 150,
    isActive: true,
  },
  {
    testId: "LAB-008",
    hospitalName: "Muzaffarpur Imaging Centre",
    name: "MRI Brain",
    category: "MRI",
    description: "Dimag ki detailed imaging — tumour, stroke, headache jaanch ke liye",
    sampleType: "N/A",
    turnaroundTime: "24 hours",
    reportDelivery: "Both",
    mrp: 8000,
    offerPrice: 5499,
    membershipDiscount: 20,
    membershipPrice: 4399,
    homeCollection: false,
    homeCollectionCharge: 0,
    fastingRequired: false,
    preparationNotes: "Koi bhi metal jewellery ya implant nahi hona chahiye",
    address: { district: "Muzaffarpur", city: "Muzaffarpur", state: "Bihar" },
    rating: 4.8,
    totalReviews: 420,
    isActive: true,
  },
];

export async function GET() {
  try {
    await connectDB();

    await LabTest.deleteMany({});
    const tests = await LabTest.insertMany(seedData);

    return NextResponse.json({
      success: true,
      message: `${tests.length} lab tests seed ho gaye!`,
      count: tests.length,
    });
  } catch (error) {
    return NextResponse.json(
      { success: false, message: "Seed error: " + error.message },
      { status: 500 }
    );
  }
}
