// Single source of truth for medical departments and surgery lists.
// Import this everywhere: admin panel, staff panel, hospital dashboard,
// doctor registration, surgery packages, AI chatbot.

// ── Medical Departments (for doctor specialization, hospital departments) ──────

export const MEDICAL_DEPARTMENTS: string[] = [
  "General Medicine",
  "General Surgery",
  "Pediatrics",
  "Gynecology & Obstetrics",
  "Orthopedics",
  "Cardiology",
  "Cardiac Surgery",
  "Neurology",
  "Neurosurgery",
  "Dermatology",
  "ENT (Ear, Nose, Throat)",
  "Ophthalmology",
  "Urology",
  "Nephrology",
  "Gastroenterology",
  "Hepatology",
  "Pulmonology",
  "Endocrinology",
  "Oncology",
  "Hematology",
  "Rheumatology",
  "Psychiatry",
  "Psychology",
  "Radiology",
  "Pathology",
  "Anesthesiology",
  "Dentistry",
  "Physiotherapy",
  "Plastic & Reconstructive Surgery",
  "Vascular Surgery",
  "Proctology",
  "Neonatology",
  "Geriatrics",
  "Palliative Care",
  "Sports Medicine",
  "Dietetics & Nutrition",
  "Other",
];

// ── Surgery Departments (categories for surgery packages) ─────────────────────

export const SURGERY_DEPARTMENTS: string[] = [
  "General Surgery",
  "Orthopedic Surgery",
  "Cardiac Surgery",
  "Neurosurgery",
  "Gynecology & Obstetrics",
  "Urology",
  "Oncology Surgery",
  "Ophthalmology",
  "ENT Surgery",
  "Dental & Maxillofacial",
  "Plastic & Reconstructive Surgery",
  "Vascular Surgery",
  "Pediatric Surgery",
  "Proctology",
  "Laparoscopic Surgery",
  "Other",
];

// ── Surgery Names grouped by Surgery Department ───────────────────────────────

export const SURGERIES_BY_DEPARTMENT: Record<string, string[]> = {
  "General Surgery": [
    "Appendectomy (Appendix Removal)",
    "Laparoscopic Hernia Repair",
    "Inguinal Hernia Repair",
    "Umbilical Hernia Repair",
    "Incisional Hernia Repair",
    "Cholecystectomy (Gallbladder Removal)",
    "Laparoscopic Cholecystectomy",
    "Hemorrhoidectomy (Piles Surgery)",
    "Stapler Hemorrhoidectomy",
    "Fistula-in-Ano Surgery",
    "Fissure Surgery (LIS)",
    "Pilonidal Sinus Surgery",
    "Thyroidectomy (Thyroid Removal)",
    "Parathyroidectomy",
    "Varicose Vein Surgery",
    "Laser Varicose Vein Treatment",
    "Adult Circumcision",
    "Hydrocele Surgery",
    "Varicocele Surgery",
    "Lipoma Removal",
    "Sebaceous Cyst Removal",
    "Abscess Drainage & Debridement",
    "Mastectomy (Breast Removal)",
    "Lumpectomy (Breast Lump)",
    "Splenectomy",
    "Pancreatectomy",
    "Gastric Bypass Surgery",
    "Sleeve Gastrectomy (Bariatric)",
    "Esophageal Surgery",
    "Intestinal Resection",
    "Colostomy",
    "Ileostomy",
    "Exploratory Laparotomy",
    "Biopsy (Surgical)",
  ],

  "Orthopedic Surgery": [
    "Total Knee Replacement (TKR)",
    "Partial Knee Replacement (UKR)",
    "Total Hip Replacement (THR)",
    "Hip Resurfacing",
    "Shoulder Replacement",
    "Elbow Replacement",
    "Ankle Replacement",
    "ACL Reconstruction",
    "PCL Reconstruction",
    "Meniscus Repair",
    "Meniscectomy",
    "Shoulder Arthroscopy",
    "Knee Arthroscopy",
    "Lumbar Disc Surgery (Microdiscectomy)",
    "Lumbar Spine Fusion",
    "Cervical Disc Surgery (ACDF)",
    "Cervical Spine Fusion",
    "Spine Decompression (Laminectomy)",
    "Scoliosis Correction Surgery",
    "Fracture Fixation (ORIF)",
    "Intramedullary Nailing",
    "Bone Grafting",
    "Osteotomy",
    "Bunion Surgery (Hallux Valgus)",
    "Carpal Tunnel Release",
    "Trigger Finger Release",
    "Rotator Cuff Repair",
    "Bankart Repair (Shoulder Dislocation)",
    "Tendon Repair",
    "Limb Lengthening Surgery",
    "Clubfoot Correction",
    "Amputation",
  ],

  "Cardiac Surgery": [
    "Coronary Artery Bypass Grafting (CABG)",
    "Off-Pump CABG (Beating Heart Surgery)",
    "Aortic Valve Replacement (AVR)",
    "Mitral Valve Replacement (MVR)",
    "Mitral Valve Repair",
    "Tricuspid Valve Repair",
    "Double Valve Replacement",
    "Aortic Aneurysm Repair",
    "Pacemaker Implantation",
    "ICD (Defibrillator) Implant",
    "ASD Closure (Atrial Septal Defect)",
    "VSD Closure (Ventricular Septal Defect)",
    "PDA Ligation",
    "Coronary Angioplasty (PTCA/Stenting)",
    "Atrial Fibrillation Ablation",
    "Heart Transplant",
    "Pericardiectomy",
    "Cardiac Tumor Removal (Myxoma)",
    "Pulmonary Endarterectomy",
    "TAVI (Transcatheter Aortic Valve)",
    "MitraClip Procedure",
    "Left Ventricular Assist Device (LVAD)",
  ],

  "Neurosurgery": [
    "Brain Tumor Surgery",
    "Craniotomy",
    "Cranioplasty",
    "Hydrocephalus Shunt (VP Shunt)",
    "Burr Hole Surgery",
    "Skull Fracture Repair",
    "Lumbar Disc Surgery (Discectomy)",
    "Cervical Disc Surgery (ACDF)",
    "Spinal Cord Decompression",
    "Spinal Fusion Surgery",
    "Deep Brain Stimulation (DBS)",
    "Epilepsy Surgery",
    "Pituitary Tumor Surgery",
    "AVM (Arteriovenous Malformation) Surgery",
    "Carotid Endarterectomy",
    "Stereotactic Biopsy",
    "Gamma Knife Radiosurgery",
    "Peripheral Nerve Surgery",
    "Carpal Tunnel Decompression (Neuro)",
    "Trigeminal Neuralgia Surgery",
  ],

  "Gynecology & Obstetrics": [
    "Caesarean Section (C-Section)",
    "Normal Delivery (Episiotomy)",
    "Hysterectomy (Uterus Removal)",
    "Laparoscopic Hysterectomy",
    "Vaginal Hysterectomy",
    "Myomectomy (Fibroid Removal)",
    "Laparoscopic Myomectomy",
    "Ovarian Cystectomy",
    "Laparoscopic Ovarian Cystectomy",
    "D&C (Dilation & Curettage)",
    "Tubal Ligation (Female Sterilization)",
    "Laparoscopic Sterilization",
    "Endometriosis Surgery",
    "LEEP Procedure (Cervix)",
    "Cervical Cerclage",
    "Vaginal Repair (Colporrhaphy)",
    "Pelvic Floor Repair",
    "Hymenoplasty",
    "Vaginoplasty",
    "Bartholin Cyst Surgery",
    "Ectopic Pregnancy Surgery",
    "Polycystic Ovary (PCOS) Surgery",
    "IVF & Assisted Reproduction",
    "Laparoscopic Diagnostic",
    "Fertility-Enhancing Surgery",
  ],

  "Urology": [
    "Kidney Stone Removal (PCNL)",
    "Kidney Stone (URSL - Ureteroscopy)",
    "Kidney Stone (ESWL - Lithotripsy)",
    "Nephrectomy (Kidney Removal)",
    "Partial Nephrectomy",
    "Pyeloplasty",
    "Prostate Surgery (TURP)",
    "Laser Prostate Surgery (HoLEP)",
    "Prostatectomy",
    "Cystoscopy",
    "Bladder Stone Removal (TURBT)",
    "Bladder Tumor Surgery",
    "Ureteroscopy (URS)",
    "Urethral Stricture Surgery",
    "Urethroplasty",
    "Vasectomy",
    "Vasectomy Reversal",
    "Orchidopexy (Undescended Testis)",
    "Varicocelectomy",
    "Penile Prosthesis Implant",
    "Circumcision (Urology)",
    "Adrenalectomy",
    "Renal Transplant",
  ],

  "Oncology Surgery": [
    "Breast Cancer Surgery (Mastectomy)",
    "Breast-Conserving Surgery (Lumpectomy)",
    "Axillary Lymph Node Dissection",
    "Colorectal Cancer Surgery",
    "Colon Resection",
    "Rectal Cancer Surgery",
    "Lung Cancer Surgery (Lobectomy)",
    "Pneumonectomy",
    "Prostate Cancer Surgery (Radical Prostatectomy)",
    "Cervical Cancer Surgery",
    "Ovarian Cancer Surgery",
    "Endometrial Cancer Surgery",
    "Thyroid Cancer Surgery",
    "Oral Cancer Surgery",
    "Tongue Cancer Surgery",
    "Laryngeal Cancer Surgery",
    "Esophageal Cancer Surgery",
    "Stomach Cancer Surgery (Gastrectomy)",
    "Liver Cancer Surgery (Hepatectomy)",
    "Pancreatic Cancer Surgery (Whipple)",
    "Kidney Cancer Surgery",
    "Bladder Cancer Surgery",
    "Soft Tissue Sarcoma Surgery",
    "Bone Cancer Surgery",
    "Melanoma Surgery",
    "Lymph Node Biopsy / Dissection",
    "Debulking Surgery",
    "Port-a-Cath Placement",
  ],

  "Ophthalmology": [
    "Cataract Surgery (Phacoemulsification)",
    "Cataract Surgery (Manual SICS)",
    "Premium IOL Implant (Multifocal/Toric)",
    "LASIK Eye Surgery",
    "SMILE Eye Surgery",
    "PRK (Photorefractive Keratectomy)",
    "Pterygium Surgery",
    "Glaucoma Surgery (Trabeculectomy)",
    "Glaucoma Laser (SLT/ALT)",
    "Retinal Detachment Repair",
    "Vitrectomy",
    "Macular Hole Surgery",
    "Anti-VEGF Injection (Avastin/Lucentis)",
    "DCR Surgery (Dacryocystorhinostomy)",
    "Squint Correction Surgery",
    "Eyelid Surgery (Ptosis Correction)",
    "Chalazion Removal",
    "Enucleation (Eye Removal)",
    "Corneal Transplant (Keratoplasty)",
    "Oculoplasty",
    "Orbital Decompression",
  ],

  "ENT Surgery": [
    "Tonsillectomy (Tonsil Removal)",
    "Adenoidectomy (Adenoid Removal)",
    "Tonsillectomy & Adenoidectomy (T&A)",
    "Septoplasty (Deviated Nasal Septum)",
    "Rhinoplasty (Nose Reshaping)",
    "FESS (Functional Endoscopic Sinus Surgery)",
    "Nasal Polypectomy",
    "Turbinoplasty (Turbinate Reduction)",
    "Tympanoplasty (Ear Drum Repair)",
    "Mastoidectomy",
    "Myringotomy (Ear Tube)",
    "Stapedotomy (Otosclerosis)",
    "Cochlear Implant",
    "BAHA (Bone-Anchored Hearing Aid)",
    "Parotidectomy",
    "Submandibular Gland Removal",
    "Neck Dissection",
    "Thyroglossal Cyst Removal",
    "Branchial Cyst Removal",
    "Microlaryngoscopy",
    "Direct Laryngoscopy",
    "Tracheostomy",
    "Uvulopalatopharyngoplasty (UPPP - Sleep Apnea)",
    "Endoscopic DCR",
  ],

  "Dental & Maxillofacial": [
    "Wisdom Tooth Extraction (Impacted)",
    "Tooth Extraction",
    "Dental Implant",
    "Full Mouth Rehabilitation",
    "Root Canal Treatment (RCT)",
    "Dental Crown & Bridge",
    "Jaw Surgery (Orthognathic Surgery)",
    "Cleft Lip Repair",
    "Cleft Palate Repair",
    "TMJ Surgery (Jaw Joint)",
    "Gum Surgery (Gingivectomy/Flap)",
    "Bone Grafting (Dental)",
    "Sinus Lift (Dental)",
    "Cyst Enucleation (Jaw)",
    "Facial Fracture Surgery",
    "Salivary Gland Surgery",
    "Oral Cancer Surgery",
  ],

  "Plastic & Reconstructive Surgery": [
    "Rhinoplasty (Nose Job)",
    "Facelift (Rhytidectomy)",
    "Brow Lift",
    "Eyelid Surgery (Blepharoplasty)",
    "Ear Reshaping (Otoplasty)",
    "Liposuction",
    "Tummy Tuck (Abdominoplasty)",
    "Brazilian Butt Lift (BBL)",
    "Breast Augmentation (Implants)",
    "Breast Reduction (Reduction Mammoplasty)",
    "Breast Lift (Mastopexy)",
    "Gynecomastia Surgery (Male Breast)",
    "Body Contouring",
    "Scar Revision Surgery",
    "Keloid Removal",
    "Burn Skin Grafting",
    "Flap Surgery (Reconstructive)",
    "Microsurgery (Replantation)",
    "Hand Reconstruction",
    "Cleft Lip & Palate (Plastic)",
    "Hair Transplant (FUE/FUT)",
    "Fat Grafting",
    "Vaginal Rejuvenation (Labiaplasty)",
    "Post-Bariatric Body Contouring",
  ],

  "Vascular Surgery": [
    "Varicose Vein Surgery (Open)",
    "Endovenous Laser Ablation (EVLA)",
    "Sclerotherapy",
    "Carotid Endarterectomy",
    "Aortic Aneurysm Repair (Open)",
    "Endovascular Aortic Repair (EVAR)",
    "Peripheral Artery Bypass",
    "Peripheral Angioplasty & Stenting",
    "AV Fistula Creation (Dialysis)",
    "AV Graft Placement",
    "Thrombectomy (Clot Removal)",
    "Embolectomy",
    "Amputation",
    "Lymph Node Surgery",
    "Deep Vein Thrombosis (DVT) Surgery",
  ],

  "Pediatric Surgery": [
    "Appendectomy (Pediatric)",
    "Hernia Repair (Pediatric)",
    "Hydrocele Repair (Pediatric)",
    "Orchidopexy (Undescended Testes)",
    "Circumcision (Pediatric)",
    "Cleft Lip Repair (Pediatric)",
    "Cleft Palate Repair (Pediatric)",
    "Hypospadias Repair",
    "Tracheoesophageal Fistula Repair",
    "Intestinal Atresia Repair",
    "Hirschsprung Disease Surgery",
    "Imperforate Anus Surgery",
    "Pyloric Stenosis (Pyloromyotomy)",
    "Necrotizing Enterocolitis (NEC) Surgery",
    "Wilms Tumor Surgery",
    "Neuroblastoma Surgery",
    "Congenital Heart Surgery (Pediatric)",
    "VP Shunt (Pediatric)",
    "Spina Bifida Surgery",
    "Clubfoot Surgery",
  ],

  "Proctology": [
    "Hemorrhoidectomy (Piles Open Surgery)",
    "Stapler Hemorrhoidectomy",
    "Laser Piles Surgery",
    "Fistula-in-Ano Surgery (Fistulectomy)",
    "Seton Placement (Fistula)",
    "Laser Fistula Treatment (FiLaC)",
    "Anal Fissure Surgery (LIS)",
    "Pilonidal Sinus Surgery",
    "Laser Pilonidal Sinus",
    "Rectal Prolapse Surgery",
    "Anal Polyp Removal",
    "Anal Cancer Surgery",
    "Colostomy / Ileostomy",
    "Sacrococcygeal Teratoma Surgery",
  ],

  "Laparoscopic Surgery": [
    "Laparoscopic Appendectomy",
    "Laparoscopic Cholecystectomy",
    "Laparoscopic Hernia Repair",
    "Laparoscopic Hysterectomy",
    "Laparoscopic Myomectomy",
    "Laparoscopic Ovarian Cystectomy",
    "Laparoscopic Nephrectomy",
    "Laparoscopic Splenectomy",
    "Laparoscopic Fundoplication (GERD)",
    "Laparoscopic Colectomy",
    "Laparoscopic Gastric Bypass",
    "Laparoscopic Sleeve Gastrectomy",
    "Laparoscopic Adrenalectomy",
    "Laparoscopic Pyloromyotomy",
    "Robotic Surgery (Laparoscopic)",
    "Diagnostic Laparoscopy",
  ],

  "Other": [],
};

// ── Helper functions ───────────────────────────────────────────────────────────

export function getSurgeries(department: string): string[] {
  return SURGERIES_BY_DEPARTMENT[department] || [];
}

export function getAllSurgeries(): string[] {
  return Object.values(SURGERIES_BY_DEPARTMENT).flat();
}

// Flat mapping: surgery name → department (for reverse lookup)
export function getSurgeryDepartment(surgeryName: string): string | undefined {
  for (const [dept, list] of Object.entries(SURGERIES_BY_DEPARTMENT)) {
    if (list.includes(surgeryName)) return dept;
  }
  return undefined;
}
